[window]
opacity = 0.9

[font]
size = 14
# normal = { family = "Cascadia Code" }
# normal = { family = "Operator Mono Book" }
# normal = { family = "Comic Code" }
# normal = { family = "Hack Nerd Font Mono" }
# normal = { family = "RobotoMono Nerd Font" }
normal = { family = "JetBrainsMono Nerd Font Mono" }

[mouse]
hide_when_typing = true

[general]
import = [
    # "~/.config/alacritty/themes/themes/rose_pine_moon.toml.toml"
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]
