# theme="rose_pine_moon"
# theme = "gruvbox_material_dark_soft"
# theme = "boo_berry"
# theme = "solarized_dark"
theme = "tokyonight_storm"

[editor]
cursorline = false
line-number = "relative"
true-color = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"C-[" = "normal_mode"
0 = "goto_line_start"
C-s = ":w"
f = "no_op"

[keys.select]
"C-[" = "normal_mode"
0 = "goto_line_start"

[keys.insert]
"C-[" = "normal_mode"
C-l = "move_char_right"
C-h = "move_char_left"

# Not support so far
# [keys.picker] 
# "C-[" = "normal_mode"
