unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-space
set -g mouse on
set -g mode-keys vi

# Naviagte panes/vim
bind h select-pane -L
bind n select-pane -D
bind e select-pane -U
bind i select-pane -R

# Split window
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind '"' split-window -h -c "#{pane_current_path}"
bind % split-window -v -c "#{pane_current_path}"

set extended-keys on

set -g base-index 1
set -g focus-events on
set -g renumber-windows on
set -s escape-time 0
set-option -g status-position top

# https://github.com/craftzdog/solarized-osaka.nvim?ref=devas.life
# Undercurl
set -g default-terminal "xterm-256color"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

set-environment -g COLORTERM "truecolor"
set -ga terminal-overrides ",*256col*:Tc"
set -as terminal-features ",alacritty:RGB"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# theme config
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_window_status_separator ' '
set -g @rose_pine_disable_active_window_menu 'on'
set -g @rose_pine_date_time '%Y-%m-%d %H:%M'
set -g @rose_pine_window_count '5'

run '~/.tmux/plugins/tpm/tpm'
