unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-space
set -g mouse on
set -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g base-index 1
set -s escape-time 0
set-option -g status-position top

# https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95
# set -g default-terminal "tmux-256color"
# set -g default-terminal 'xterm-kitty'
# set-option -sa terminal-features ',alacritty:RGB'
# set-option -ga terminal-features ",alacritty:usstyle"

# https://github.com/craftzdog/solarized-osaka.nvim?ref=devas.life
# Undercurl
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Alacritty
set -as terminal-features ",alacritty:RGB"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'jimeh/tmuxifier'

# theme config
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_window_status_separator ' '
set -g @rose_pine_disable_active_window_menu 'on'
set -g @rose_pine_date_time '%Y-%m-%d %H:%M'
set -g @rose_pine_window_count '5'

run '~/.tmux/plugins/tpm/tpm'
